---
- include: "{{ jenkins_install_via }}/stop.yml"
- include: "{{ jenkins_install_via }}/install.yml"

# use a configuration with disabled security otherwise the plugin installation
# will fail on a re-run, as security is configured in a later step
- include: "pre-configure-jenkins.yml"

- include: "{{ jenkins_install_via }}/start.yml"
- include: "configure-plugins.yml"

- include: "configure-jobs.yml"
- include: "{{ jenkins_after_config_jobs_file | default('empty.yml') }}"

# Jenkins should not be running while we change the configuration
# data, otherwise some files might be overwritten when it restarts
- include: "{{ jenkins_install_via }}/stop.yml"
- include: "post-configure-jenkins.yml"

- include: "{{ jenkins_install_via }}/start.yml"
