---
- name: "Verify Ansible meets version requirements"
  assert:
    that: "ansible_version.full | version_compare('2.1', '>=')"
    msg: "Ansible version must be >= 2.1 but it is {{ ansible_version.full }}"

- name: "Install Java and Git"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java
    - git

- name: "Add Jenkins repository"
  yum_repository:
    name: jenkins
    description: "official Jenkins repository"
    baseurl: "http://pkg.jenkins-ci.org/redhat"
    gpgkey: "https://pkg.jenkins.io/redhat/jenkins-ci.org.key"
    gpgcheck: yes

- name: "Install Jenkins"
  yum:
    name: "jenkins-{{ jenkins_version }}"
    state: present

- name: "Set Jenkins home"
  lineinfile:
    dest: "/etc/sysconfig/jenkins"
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='

- name: "Set Java options"
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS=\"{{ jenkins_java_opts }}\""

- name: "Set Jenkins port"
  lineinfile:
    dest: "/etc/sysconfig/jenkins"
    regexp: '^JENKINS_PORT='
    line: 'JENKINS_PORT="{{ jenkins_port }}"'
