- name: "Make sure Jenkins is stopped"
  service:
    name: jenkins
    state: stopped
  ignore_errors: yes

- name: "Create Jenkins group"
  group:
    name: "{{ jenkins_config_group }}"
    state: present

- name: "Create Jenkins user"
  user: name="{{ jenkins_config_owner }}" groups="{{ jenkins_config_group }}" state="present"

- name: "Install Java and Git"
  yum: name="java" state="present"
  with_items:
    - java
    - git

- name: "Add Jenkins repository"
  yum_repository:
    name: "jenkins"
    description: "official Jenkins repository"
    baseurl: "http://pkg.jenkins-ci.org/redhat"
    gpgkey: "https://pkg.jenkins.io/redhat/jenkins-ci.org.key"
    gpgcheck: yes

- name: "Install Jenkins"
  yum:
    name: "jenkins-{{ jenkins_version }}"
    state: present

- name: Set JENKINS_HOME
  lineinfile:
    create: "yes"
    dest: "/etc/sysconfig/jenkins"
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='
    state: "present"

- name: "Set Jenkins command line options"
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS=\"{{ jenkins_java_opts }}\""

- name: "Set Jenkins port"
  lineinfile:
    dest: "/etc/sysconfig/jenkins"
    regexp: '^JENKINS_PORT='
    line: 'JENKINS_PORT="{{ jenkins_port }}"'
