---
- name: "Stop Jenkins"
  service:
    name: "jenkins"
    state: "stopped"
  ignore_errors: yes
  register: result
  failed_when: "result.failed is defined and result.failed == true and 'could not find the requested service' not in (result.msg|lower)"
